// frontend/JinaBae/react-test-app/src/App.tsx
import React from "react";
import ReactDOM from "react-dom/client";

import "./index.css";
import HelloPropsTest from "./basics/HelloPropsTest.tsx";
import SimpleCounter from "./basics/SimpleCounter.tsx";
import ConditionalRenderTest from "./basics/ConditionalRenderTest.tsx";

const App = () => (
    <div className="mt-10 text-3xl mx-auto max-w-6xl">
        <HelloPropsTest/>
        <div>Name: navigation-bar-app</div>
        <div>Framework: react-18</div>
        <SimpleCounter/>
        <ConditionalRenderTest/>
    </div>
);

export default App

// frontend/JihanKim/vue-board-app/src/App.vue
<template>
  <div class="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: vue-board-app</div>
    <div>Framework: vue3</div>
  </div>
</template>

<script lang="ts">
  import { defineComponent } from "vue";
  import mitt from 'mitt';
  const eventBus = mitt();
  export default defineComponent({});
</script>
