// frontend/YoungseongPark/navigation-bar-app/src/App.tsx
import React from "react";
import ReactDOM from "react-dom/client";

import "./index.css";

const App = () => (
  <div className="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: navigation-bar-app</div>
    <div>Framework: react-18</div>
  </div>
);

const root = ReactDOM.createRoot(document.getElementById("app") as HTMLElement);
root.render(<App />);

// frontend/JihanKim/vue-board-app/src/App.vue
<template>
  <div class="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: vue-board-app</div>
    <div>Framework: vue3</div>
  </div>
</template>

<script lang="ts">
  import { defineComponent } from "vue";
  import mitt from 'mitt';
  const eventBus = mitt();
  export default defineComponent({});
</script>
